; ==================================================
; PHP 8.2 – Migration mode (DEV)
; ==================================================

display_errors = On
display_startup_errors = On

log_errors = On
error_log = /proc/self/fd/2

; Afficher UNIQUEMENT les erreurs bloquantes
error_reporting = E_ALL & ~E_DEPRECATED & ~E_USER_DEPRECATED

; Mémoire (outils type PHPStan / Rector)
memory_limit = 1024M

; Date
date.timezone = Europe/Paris