--
-- PostgreSQL database dump
--

-- Dumped from database version 15.12
-- Dumped by pg_dump version 15.12

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: foncier; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA foncier;


--
-- Name: maj_dossier_nsurface(); Type: FUNCTION; Schema: foncier; Owner: -
--

CREATE FUNCTION foncier.maj_dossier_nsurface() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    WITH dossiers AS (
SELECT d.n_surface, d.pk_dossier
FROM foncier.dossier d
INNER JOIN foncier.dossier_bien db ON (db.fk_dossier = d.pk_dossier)
WHERE db.fk_bien = NEW.pk_bien
AND d.fk_type in (613, 619)
),
somme AS (
SELECT d.n_surface, db.fk_dossier, sum(b.n_surface) AS surf 
FROM foncier.bien b
INNER JOIN foncier.dossier_bien db ON (db.fk_bien = b.pk_bien)
INNER JOIN dossiers d ON (db.fk_dossier = d.pk_dossier)
GROUP BY db.fk_dossier, d.n_surface
)
UPDATE foncier.dossier d
SET n_surface = somme.surf
FROM somme 
WHERE somme.fk_dossier = d.pk_dossier;
 
    RETURN NEW;
END;
$$;


--
-- Name: maj_erreur_cadastrale(); Type: FUNCTION; Schema: foncier; Owner: -
--

CREATE FUNCTION foncier.maj_erreur_cadastrale() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN

WITH entrant AS (
SELECT fk_dossier, fk_mutation_bien, sum(b.n_surface) s
FROM foncier.dossier_bien db
LEFT JOIN foncier.dossier d ON (db.fk_dossier= d.pk_dossier)
LEFT JOIN foncier.bien b ON (db.fk_bien= b.pk_bien)
WHERE d.fk_type = 615 AND fk_mutation_bien = 644
GROUP BY fk_dossier, fk_mutation_bien),
sortant  AS (
SELECT fk_dossier, fk_mutation_bien, sum(b.n_surface) s 
FROM foncier.dossier_bien db
LEFT JOIN foncier.dossier d ON (db.fk_dossier= d.pk_dossier)
LEFT JOIN foncier.bien b ON (db.fk_bien= b.pk_bien)
WHERE d.fk_type = 615 AND fk_mutation_bien = 645
GROUP BY fk_dossier, fk_mutation_bien)

UPDATE foncier.dossier d
SET n_erreur_cadastrale = sortant.s-entrant.s
FROM entrant INNER JOIN sortant using(fk_dossier)
WHERE entrant.fk_dossier = d.pk_dossier;
 
    RETURN NEW;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: acte; Type: TABLE; Schema: foncier; Owner: -
--

CREATE TABLE foncier.acte (
    pk_acte integer NOT NULL,
    fk_service_publicitaire integer,
    fk_geometre integer,
    fk_occupant integer,
    dt_acte timestamp without time zone,
    dt_publication timestamp without time zone,
    n_montant_initial double precision,
    s_volume character varying(255),
    s_numero_acte character varying(255),
    s_numero_convention character varying(255)
);


--
-- Name: acte_pk_acte_seq; Type: SEQUENCE; Schema: foncier; Owner: -
--

ALTER TABLE foncier.acte ALTER COLUMN pk_acte ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME foncier.acte_pk_acte_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authentification; Type: TABLE; Schema: foncier; Owner: -
--

CREATE TABLE foncier.authentification (
    pk_authentification integer NOT NULL,
    fk_utilisateur integer NOT NULL,
    b_is_admin boolean DEFAULT false,
    s_login character varying(255),
    s_password character varying(255),
    fk_liste_profil integer
);


--
-- Name: authentification_pk_authentification_seq; Type: SEQUENCE; Schema: foncier; Owner: -
--

ALTER TABLE foncier.authentification ALTER COLUMN pk_authentification ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME foncier.authentification_pk_authentification_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bien; Type: TABLE; Schema: foncier; Owner: -
--

CREATE TABLE foncier.bien (
    pk_bien integer NOT NULL,
    fk_bien_lie integer,
    fk_type_bien integer,
    fk_statut integer,
    fk_utilisateur integer,
    s_nom_bien character varying(255),
    s_voie character varying(255),
    s_code_insee character varying(255),
    n_surface integer,
    b_stock boolean,
    dt_creation timestamp without time zone,
    dt_modification timestamp without time zone,
    dt_suppression timestamp without time zone,
    s_provenance character varying(50),
    s_nom_bien_ini character varying(256),
    fk_patrimoine integer,
    s_commentaire text,
    b_bati boolean,
    d_demolition date,
    id_zac integer
);


--
-- Name: bien_pk_bien_seq; Type: SEQUENCE; Schema: foncier; Owner: -
--

ALTER TABLE foncier.bien ALTER COLUMN pk_bien ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME foncier.bien_pk_bien_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cadastre_parcelles_historique; Type: TABLE; Schema: foncier; Owner: -
--

CREATE TABLE foncier.cadastre_parcelles_historique (
    pk_bien integer,
    s_nom_bien character varying(255),
    geojson text,
    x double precision,
    y double precision
);


--
-- Name: commune; Type: TABLE; Schema: foncier; Owner: -
--

CREATE TABLE foncier.commune (
    pk_commune integer NOT NULL,
    s_code_insee character varying(255),
    s_nom character varying(255),
    fk_patrimoine integer
);


--
-- Name: commune_pk_commune_seq; Type: SEQUENCE; Schema: foncier; Owner: -
--

ALTER TABLE foncier.commune ALTER COLUMN pk_commune ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME foncier.commune_pk_commune_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contact; Type: TABLE; Schema: foncier; Owner: -
--

CREATE TABLE foncier.contact (
    pk_contact integer NOT NULL,
    s_groupe character varying(64) DEFAULT 'default'::character varying NOT NULL,
    s_nom character varying(255) NOT NULL,
    s_adresse character varying(255),
    s_code_postal character varying(50),
    s_telephone character varying(20),
    s_email character varying(255),
    s_siret character varying(32),
    s_siren character varying(32),
    s_token_entreprise character varying(38),
    s_ville character varying(255),
    n_latitude double precision,
    n_longitude double precision,
    dt_creation timestamp without time zone,
    dt_suppression timestamp without time zone,
    fk_type_personne integer
);


--
-- Name: contact_pk_contact_seq; Type: SEQUENCE; Schema: foncier; Owner: -
--

ALTER TABLE foncier.contact ALTER COLUMN pk_contact ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME foncier.contact_pk_contact_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: document; Type: TABLE; Schema: foncier; Owner: -
--

CREATE TABLE foncier.document (
    pk_document integer NOT NULL,
    s_perimetre character varying(64) NOT NULL,
    fk_reference integer,
    fk_fichier character varying(255) NOT NULL,
    fk_utilisateur integer,
    dt_creation timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: document_pk_document_seq; Type: SEQUENCE; Schema: foncier; Owner: -
--

ALTER TABLE foncier.document ALTER COLUMN pk_document ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME foncier.document_pk_document_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dossier; Type: TABLE; Schema: foncier; Owner: -
--

CREATE TABLE foncier.dossier (
    pk_dossier integer NOT NULL,
    fk_type integer,
    fk_patrimoine integer,
    fk_operation integer,
    fk_notaire integer,
    fk_mode_dmpc integer,
    fk_utilisateur integer,
    fk_acte integer,
    fk_acteur integer,
    fk_provenance_transaction integer,
    s_nom_dossier character varying(255),
    s_code_insee character varying(255),
    n_numero_dmpc integer,
    n_montant_transaction double precision,
    s_code_analytique character varying(255),
    s_reference_cadastrale text,
    n_surface integer,
    s_commentaire text,
    dt_creation timestamp without time zone,
    dt_suppression timestamp without time zone,
    dt_modification timestamp without time zone,
    n_erreur_cadastrale integer,
    s_provenance character varying(50),
    s_code_insee_supplementaire character varying(255) DEFAULT NULL::character varying,
    fk_lot integer,
    n_depot_garantie integer
);


--
-- Name: dossier_acteur; Type: TABLE; Schema: foncier; Owner: -
--

CREATE TABLE foncier.dossier_acteur (
    pk_dossier_acteur integer NOT NULL,
    fk_type integer,
    fk_categorie integer,
    s_nom character varying(255),
    s_prenom character varying(255),
    fk_dossier integer,
    dt_fin_acteur date,
    s_siren character varying(14)
);


--
-- Name: COLUMN dossier_acteur.dt_fin_acteur; Type: COMMENT; Schema: foncier; Owner: -
--

COMMENT ON COLUMN foncier.dossier_acteur.dt_fin_acteur IS 'Date de bail par exemple';


--
-- Name: dossier_acteur_pk_dossier_acteur_seq; Type: SEQUENCE; Schema: foncier; Owner: -
--

ALTER TABLE foncier.dossier_acteur ALTER COLUMN pk_dossier_acteur ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME foncier.dossier_acteur_pk_dossier_acteur_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dossier_bien; Type: TABLE; Schema: foncier; Owner: -
--

CREATE TABLE foncier.dossier_bien (
    pk_dossier_bien integer NOT NULL,
    fk_dossier integer,
    fk_bien integer,
    fk_mutation_bien integer,
    fk_mutation_dossier integer NOT NULL,
    n_mutation integer
);


--
-- Name: dossier_bien_fk_mutation_dossier_seq; Type: SEQUENCE; Schema: foncier; Owner: -
--

ALTER TABLE foncier.dossier_bien ALTER COLUMN fk_mutation_dossier ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME foncier.dossier_bien_fk_mutation_dossier_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dossier_bien_pk_dossier_bien_seq; Type: SEQUENCE; Schema: foncier; Owner: -
--

ALTER TABLE foncier.dossier_bien ALTER COLUMN pk_dossier_bien ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME foncier.dossier_bien_pk_dossier_bien_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dossier_pk_dossier_seq; Type: SEQUENCE; Schema: foncier; Owner: -
--

ALTER TABLE foncier.dossier ALTER COLUMN pk_dossier ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME foncier.dossier_pk_dossier_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: favoris; Type: TABLE; Schema: foncier; Owner: -
--

CREATE TABLE foncier.favoris (
    pk_favoris integer NOT NULL,
    fk_utilisateur integer,
    fk_bien integer,
    fk_dossier integer,
    dt_creation timestamp without time zone
);


--
-- Name: favoris_pk_favoris_seq; Type: SEQUENCE; Schema: foncier; Owner: -
--

ALTER TABLE foncier.favoris ALTER COLUMN pk_favoris ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME foncier.favoris_pk_favoris_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fichier; Type: TABLE; Schema: foncier; Owner: -
--

CREATE TABLE foncier.fichier (
    pk_fichier character varying(255) NOT NULL,
    s_path character varying(255) NOT NULL,
    s_subpath character varying(255),
    s_filename text NOT NULL,
    s_ext character varying(16) NOT NULL,
    s_type character varying(128) NOT NULL,
    n_size integer NOT NULL,
    dt_creation timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    b_temporary boolean DEFAULT true NOT NULL
);


--
-- Name: liste; Type: TABLE; Schema: foncier; Owner: -
--

CREATE TABLE foncier.liste (
    pk_liste integer NOT NULL,
    s_groupe character varying(255),
    s_clef character varying(255),
    s_valeur character varying(255),
    n_ordre integer
);


--
-- Name: liste_pk_liste_seq; Type: SEQUENCE; Schema: foncier; Owner: -
--

ALTER TABLE foncier.liste ALTER COLUMN pk_liste ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME foncier.liste_pk_liste_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: logger; Type: TABLE; Schema: foncier; Owner: -
--

CREATE TABLE foncier.logger (
    pk_logger integer NOT NULL,
    fk_utilisateur integer,
    s_message text,
    s_level_name character varying(100),
    s_client_ip character varying(80),
    s_client_port character varying(50),
    s_uri text,
    s_query_string text,
    s_method character varying(50),
    s_system text,
    s_user_agent text,
    dt_creation timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: logger_pk_logger_seq; Type: SEQUENCE; Schema: foncier; Owner: -
--

ALTER TABLE foncier.logger ALTER COLUMN pk_logger ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME foncier.logger_pk_logger_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: operation; Type: TABLE; Schema: foncier; Owner: -
--

CREATE TABLE foncier.operation (
    pk_operation integer NOT NULL,
    s_nom character varying(64)
);


--
-- Name: operation_pk_operation_seq; Type: SEQUENCE; Schema: foncier; Owner: -
--

ALTER TABLE foncier.operation ALTER COLUMN pk_operation ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME foncier.operation_pk_operation_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: utilisateur; Type: TABLE; Schema: foncier; Owner: -
--

CREATE TABLE foncier.utilisateur (
    pk_utilisateur integer NOT NULL,
    s_nom character varying(255),
    s_prenom character varying(255),
    s_adresse character varying(255),
    s_code_postal character varying(50),
    s_ville character varying(255),
    s_email character varying(255),
    s_telephone character varying(20),
    fk_entreprise integer,
    s_token_user text,
    dt_creation timestamp without time zone,
    dt_suppression timestamp without time zone
);


--
-- Name: utilisateur_pk_utilisateur_seq; Type: SEQUENCE; Schema: foncier; Owner: -
--

ALTER TABLE foncier.utilisateur ALTER COLUMN pk_utilisateur ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME foncier.utilisateur_pk_utilisateur_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: v_dto_authentification; Type: VIEW; Schema: foncier; Owner: -
--

CREATE VIEW foncier.v_dto_authentification AS
 SELECT authentification.pk_authentification,
    authentification.fk_utilisateur,
    utilisateur.s_nom AS s_utilisateur_nom,
    utilisateur.s_prenom AS s_utilisateur_prenom,
    authentification.fk_liste_profil,
    liste.s_clef AS s_role_libelle,
    authentification.b_is_admin,
    authentification.s_login,
    authentification.s_password
   FROM ((foncier.authentification
     LEFT JOIN foncier.utilisateur ON ((utilisateur.pk_utilisateur = authentification.fk_utilisateur)))
     LEFT JOIN foncier.liste ON ((liste.pk_liste = authentification.fk_liste_profil)));


--
-- Name: v_dto_bien; Type: VIEW; Schema: foncier; Owner: -
--

CREATE VIEW foncier.v_dto_bien AS
 SELECT DISTINCT bien.pk_bien,
    bien.fk_type_bien,
    bien.fk_bien_lie,
    bien_lie.s_nom_bien AS s_nom_bien_lie,
    upper(concat((commune.s_nom)::text, ' ', (commune.s_nom)::text, ' ', (bien.s_nom_bien)::text)) AS s_mots_clefs,
    liste_type_bien.s_valeur AS s_type_bien,
    bien.fk_patrimoine,
    COALESCE(liste_patrimoine.s_valeur, liste_commune.s_valeur) AS s_patrimoine,
    bien.fk_statut,
    liste_statut.s_valeur AS s_statut,
    bien.fk_utilisateur,
    utilisateur.s_nom AS s_utilisateur_nom,
    utilisateur.s_prenom AS s_utilisateur_prenom,
    bien.s_nom_bien,
    length((bien.s_nom_bien)::text) AS s_nom_bien_length,
    bien.s_voie,
    bien.s_code_insee,
    commune.s_nom AS s_commune,
    bien.n_surface,
    bien.b_stock,
    bien.dt_creation,
    bien.dt_modification,
    bien.dt_suppression,
    cph.geojson,
    cph.x,
    cph.y,
    bien.s_commentaire,
    bien.b_bati,
    bien.d_demolition,
    bien.id_zac AS fk_zac
   FROM ((((((((foncier.bien
     LEFT JOIN foncier.utilisateur ON ((utilisateur.pk_utilisateur = bien.fk_utilisateur)))
     LEFT JOIN foncier.commune ON (((bien.s_code_insee)::text = (commune.s_code_insee)::text)))
     LEFT JOIN foncier.liste liste_patrimoine ON ((bien.fk_patrimoine = liste_patrimoine.pk_liste)))
     LEFT JOIN foncier.liste liste_type_bien ON ((liste_type_bien.pk_liste = bien.fk_type_bien)))
     LEFT JOIN foncier.liste liste_commune ON ((liste_commune.pk_liste = commune.fk_patrimoine)))
     LEFT JOIN foncier.liste liste_statut ON ((liste_statut.pk_liste = bien.fk_statut)))
     LEFT JOIN foncier.bien bien_lie ON ((bien_lie.pk_bien = bien.fk_bien_lie)))
     LEFT JOIN foncier.cadastre_parcelles_historique cph ON ((bien.pk_bien = cph.pk_bien)));


--
-- Name: v_dto_commune; Type: VIEW; Schema: foncier; Owner: -
--

CREATE VIEW foncier.v_dto_commune AS
 SELECT commune.pk_commune,
    upper(concat(public.unaccent((commune.s_nom)::text), ' ', commune.s_code_insee, ' ', (commune.s_nom)::text)) AS s_mots_clefs,
    commune.s_code_insee,
    commune.s_nom,
    commune.fk_patrimoine,
    liste_patrimoine.s_valeur AS s_patrimoine_libelle
   FROM (foncier.commune
     LEFT JOIN foncier.liste liste_patrimoine ON ((liste_patrimoine.pk_liste = commune.fk_patrimoine)));


--
-- Name: v_dto_contact; Type: VIEW; Schema: foncier; Owner: -
--

CREATE VIEW foncier.v_dto_contact AS
 SELECT contact.pk_contact,
    upper((contact.s_groupe)::text) AS s_groupe,
    upper((contact.s_nom)::text) AS s_nom,
    contact.s_adresse,
    contact.s_code_postal,
    contact.s_telephone,
    contact.s_email,
    contact.s_siret,
    contact.s_siren,
    contact.s_token_entreprise,
    contact.s_ville,
    contact.n_latitude,
    contact.n_longitude,
    contact.dt_creation,
    contact.dt_suppression
   FROM foncier.contact;


--
-- Name: v_dto_documents; Type: VIEW; Schema: foncier; Owner: -
--

CREATE VIEW foncier.v_dto_documents AS
 SELECT fichier.pk_fichier AS fk_fichier,
    fichier.s_path,
    fichier.s_subpath,
    fichier.s_filename,
    fichier.s_ext,
    fichier.s_type,
    fichier.n_size,
    document.dt_creation,
    document.fk_reference,
    document.s_perimetre,
    fichier.b_temporary,
    document.pk_document
   FROM (foncier.fichier
     JOIN foncier.document ON (((document.fk_fichier)::text = (fichier.pk_fichier)::text)));


--
-- Name: v_dto_dossier; Type: VIEW; Schema: foncier; Owner: -
--

CREATE VIEW foncier.v_dto_dossier AS
 SELECT dossier.pk_dossier,
    upper(concat(commune.s_nom, ' ', (commune.s_nom)::text, ' ', dossier.s_nom_dossier, ' ', operation.s_nom, ' ', dossier.s_reference_cadastrale)) AS s_mots_clefs,
    upper((dossier.s_nom_dossier)::text) AS s_nom_dossier,
    dossier.fk_type,
    upper((liste_type.s_valeur)::text) AS s_type_dossier_long,
    upper((liste_type.s_clef)::text) AS s_type_dossier_short,
    commune.fk_patrimoine,
    upper((liste_patrimoine.s_valeur)::text) AS s_patrimoine,
    dossier.fk_operation,
    upper((operation.s_nom)::text) AS s_operation,
    dossier.fk_notaire,
    upper((contact_notaire.s_nom)::text) AS s_notaire,
    dossier.fk_mode_dmpc,
    upper((liste_mode_dmpc.s_valeur)::text) AS s_mode_dmpc,
    dossier.fk_utilisateur,
    upper((utilisateur.s_nom)::text) AS s_utilisateur_nom,
    upper((utilisateur.s_prenom)::text) AS s_utilisateur_prenom,
    dossier.fk_acte,
    acte.fk_service_publicitaire,
    upper((contact_service_publicite.s_nom)::text) AS s_service_pub,
    acte.fk_occupant,
    upper((contact_occupant.s_nom)::text) AS s_occupant,
    acte.fk_geometre,
    upper((contact_geometre.s_nom)::text) AS s_geometre,
    acte.dt_acte,
    acte.dt_publication,
    acte.n_montant_initial,
    upper((acte.s_volume)::text) AS s_volume,
    acte.s_numero_acte,
    acte.s_numero_convention,
    dossier.s_code_insee,
    dossier.s_code_insee_supplementaire,
    dossier.n_numero_dmpc,
    dossier.n_montant_transaction,
    dossier.fk_provenance_transaction,
    upper((liste_provenance_transaction.s_valeur)::text) AS s_provenance_transaction,
    upper((dossier.s_code_analytique)::text) AS s_code_analytique,
    dossier.n_surface,
    dossier.s_commentaire,
    upper(dossier.s_reference_cadastrale) AS s_reference_cadastrale,
    dossier.n_erreur_cadastrale,
    dossier_acteur.pk_dossier_acteur AS fk_dossier_acteur,
    dossier_acteur.fk_type AS fk_type_acteur,
    liste_type_acteur.s_valeur AS s_type_acteur_libelle,
    liste_categorie_acteur.s_valeur AS s_categorie_acteur_libelle,
    dossier_acteur.fk_categorie AS fk_categorie_acteur,
    dossier_acteur.s_nom AS s_acteur_nom,
    dossier_acteur.s_prenom AS s_acteur_prenom,
    upper(concat(dossier_acteur.s_nom, ' ', dossier_acteur.s_prenom)) AS s_acteur_nom_prenom,
    dossier_acteur.dt_fin_acteur,
    dossier.dt_creation,
    dossier.dt_suppression,
    dossier.dt_modification,
    (commune.s_nom)::text AS s_commune_minus,
    upper((commune.s_nom)::text) AS s_commune,
    upper((communesupplementaire.s_nom)::text) AS s_commune_supplementaire
   FROM ((((((((((((((((foncier.dossier
     LEFT JOIN foncier.utilisateur ON ((utilisateur.pk_utilisateur = dossier.fk_utilisateur)))
     LEFT JOIN foncier.liste liste_type ON ((liste_type.pk_liste = dossier.fk_type)))
     LEFT JOIN foncier.commune ON (((dossier.s_code_insee)::text = (commune.s_code_insee)::text)))
     LEFT JOIN foncier.commune communesupplementaire ON (((dossier.s_code_insee_supplementaire)::text = (communesupplementaire.s_code_insee)::text)))
     LEFT JOIN foncier.liste liste_patrimoine ON ((liste_patrimoine.pk_liste = commune.fk_patrimoine)))
     LEFT JOIN foncier.operation ON ((operation.pk_operation = dossier.fk_operation)))
     LEFT JOIN foncier.contact contact_notaire ON ((contact_notaire.pk_contact = dossier.fk_notaire)))
     LEFT JOIN foncier.liste liste_mode_dmpc ON ((liste_mode_dmpc.pk_liste = dossier.fk_mode_dmpc)))
     LEFT JOIN foncier.acte ON ((acte.pk_acte = dossier.fk_acte)))
     LEFT JOIN foncier.contact contact_service_publicite ON ((contact_service_publicite.pk_contact = acte.fk_service_publicitaire)))
     LEFT JOIN foncier.contact contact_occupant ON ((contact_occupant.pk_contact = acte.fk_occupant)))
     LEFT JOIN foncier.contact contact_geometre ON ((contact_geometre.pk_contact = acte.fk_geometre)))
     LEFT JOIN foncier.dossier_acteur ON ((dossier_acteur.fk_dossier = dossier.pk_dossier)))
     LEFT JOIN foncier.liste liste_type_acteur ON ((liste_type_acteur.pk_liste = dossier_acteur.fk_type)))
     LEFT JOIN foncier.liste liste_categorie_acteur ON ((liste_categorie_acteur.pk_liste = dossier_acteur.fk_categorie)))
     LEFT JOIN foncier.liste liste_provenance_transaction ON ((liste_provenance_transaction.pk_liste = dossier.fk_provenance_transaction)));


--
-- Name: v_dto_dossier_bien; Type: VIEW; Schema: foncier; Owner: -
--

CREATE VIEW foncier.v_dto_dossier_bien AS
 SELECT dossier_bien.pk_dossier_bien,
    dossier_bien.fk_dossier,
    dossier_bien.n_mutation,
    dossier.s_nom_dossier,
    dossier.n_numero_dmpc,
    dossier.s_type_dossier_short,
    liste_type_dossier_order.n_ordre AS n_ordre_type_dossier,
    dossier.s_type_dossier_long,
    dossier.dt_acte,
    dossier_bien.fk_bien,
    dossier_bien.fk_mutation_bien,
    dossier_bien.fk_mutation_dossier,
    dossier.s_notaire,
    dossier.n_montant_initial,
    dossier.s_numero_acte,
    dossier.s_volume,
    dossier.dt_publication,
    dossier.s_service_pub,
    dossier.n_erreur_cadastrale,
    liste_mutation_bien.s_valeur AS s_mutation_bien,
    liste_mutation_dossier.s_valeur AS s_mutation_dossier,
    bien.s_nom_bien,
    bien.s_patrimoine,
    bien.s_statut,
    bien.n_surface,
    bien.s_type_bien,
    bien.s_commune,
    bien.s_voie,
    bien.b_stock,
    dossier_acteur.s_nom AS s_nom_acteur,
    dossier_acteur.s_prenom AS s_prenom_acteur,
    COALESCE(dossier.s_code_analytique, 'inconnu'::text) AS s_code_analytique
   FROM ((((((foncier.dossier_bien
     LEFT JOIN foncier.v_dto_dossier dossier ON ((dossier.pk_dossier = dossier_bien.fk_dossier)))
     LEFT JOIN foncier.v_dto_bien bien ON ((bien.pk_bien = dossier_bien.fk_bien)))
     LEFT JOIN foncier.liste liste_mutation_bien ON ((liste_mutation_bien.pk_liste = dossier_bien.fk_mutation_bien)))
     LEFT JOIN foncier.liste liste_type_dossier_order ON ((liste_type_dossier_order.pk_liste = dossier.fk_type)))
     LEFT JOIN foncier.liste liste_mutation_dossier ON ((liste_mutation_dossier.pk_liste = dossier_bien.fk_mutation_dossier)))
     LEFT JOIN foncier.dossier_acteur ON (((dossier_acteur.fk_dossier = dossier_bien.fk_dossier) AND (dossier_acteur.fk_type IN ( SELECT liste.pk_liste
           FROM foncier.liste
          WHERE (((liste.s_groupe)::text = 'acteur.type'::text) AND ((liste.s_clef)::text = ANY ((ARRAY['vendeur'::character varying, 'acquéreur'::character varying, 'locataire'::character varying])::text[]))))))));


--
-- Name: v_dto_favoris; Type: VIEW; Schema: foncier; Owner: -
--

CREATE VIEW foncier.v_dto_favoris AS
 SELECT favoris.pk_favoris,
    favoris.fk_bien,
    favoris.fk_dossier,
    bien.fk_type_bien,
    liste_type_bien.s_valeur AS s_type_bien,
    bien.s_nom_bien,
    commune_bien.s_nom AS s_commune_bien,
    commune_bien.fk_patrimoine AS fk_patrimoine_bien,
    liste_patrimoine_bien.s_valeur AS s_patrimoine_bien,
    bien.b_stock,
    dossier.s_nom_dossier,
    commune_dossier.s_nom AS s_commune_dossier,
    dossier.fk_type AS fk_type_dossier,
    liste_type.s_valeur AS s_type_dossier_long,
    liste_type.s_clef AS s_type_dossier_short,
    acte.dt_acte AS dt_acte_dossier,
    favoris.fk_utilisateur,
    favoris.dt_creation
   FROM ((((((((foncier.favoris favoris
     LEFT JOIN foncier.dossier dossier ON ((dossier.pk_dossier = favoris.fk_dossier)))
     LEFT JOIN foncier.commune commune_dossier ON (((commune_dossier.s_code_insee)::text = (dossier.s_code_insee)::text)))
     LEFT JOIN foncier.liste liste_type ON ((liste_type.pk_liste = dossier.fk_type)))
     LEFT JOIN foncier.acte acte ON ((acte.pk_acte = dossier.fk_acte)))
     LEFT JOIN foncier.bien bien ON ((bien.pk_bien = favoris.fk_bien)))
     LEFT JOIN foncier.liste liste_type_bien ON ((liste_type_bien.pk_liste = bien.fk_type_bien)))
     LEFT JOIN foncier.commune commune_bien ON (((commune_bien.s_code_insee)::text = (bien.s_code_insee)::text)))
     LEFT JOIN foncier.liste liste_patrimoine_bien ON ((liste_patrimoine_bien.pk_liste = commune_bien.fk_patrimoine)));


--
-- Name: v_dto_liste; Type: VIEW; Schema: foncier; Owner: -
--

CREATE VIEW foncier.v_dto_liste AS
 SELECT liste.pk_liste,
    liste.s_groupe,
    liste.s_clef,
    liste.s_valeur,
    liste.n_ordre
   FROM foncier.liste;


--
-- Name: v_dto_operation; Type: VIEW; Schema: foncier; Owner: -
--

CREATE VIEW foncier.v_dto_operation AS
 SELECT operation.pk_operation,
    upper((operation.s_nom)::text) AS s_nom
   FROM foncier.operation;


--
-- Name: v_dto_rapport_build; Type: VIEW; Schema: foncier; Owner: -
--

CREATE VIEW foncier.v_dto_rapport_build AS
 SELECT dossier_bien.pk_dossier_bien,
    dossier_bien.fk_dossier,
    dossier_bien.fk_bien,
    concat(dossier_bien.fk_dossier, '*', dossier_bien.n_mutation) AS s_dossier_id_mutation,
    liste_mutation_bien.s_valeur AS s_mutation_bien_libelle
   FROM (foncier.dossier_bien
     JOIN foncier.liste liste_mutation_bien ON ((liste_mutation_bien.pk_liste = dossier_bien.fk_mutation_bien)));


--
-- Name: v_dto_utilisateur; Type: VIEW; Schema: foncier; Owner: -
--

CREATE VIEW foncier.v_dto_utilisateur AS
 SELECT utilisateur.pk_utilisateur,
    utilisateur.s_nom AS s_utilisateur_nom,
    utilisateur.s_prenom AS s_utilisateur_prenom,
    liste_role.s_clef AS s_role,
    utilisateur.s_adresse AS s_utilisateur_adresse,
    utilisateur.s_code_postal AS s_utilisateur_code_postal,
    utilisateur.s_ville AS s_utilisateur_ville,
    utilisateur.s_email AS s_utilisateur_email,
    utilisateur.s_telephone AS s_utilisateur_telephone,
    utilisateur.s_token_user,
    utilisateur.dt_creation,
    utilisateur.dt_suppression
   FROM ((foncier.utilisateur
     LEFT JOIN foncier.authentification ON ((authentification.fk_utilisateur = utilisateur.pk_utilisateur)))
     LEFT JOIN foncier.liste liste_role ON ((liste_role.pk_liste = authentification.fk_liste_profil)));


--
-- Name: authentification idx_authentification; Type: CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.authentification
    ADD CONSTRAINT idx_authentification UNIQUE (s_login);


--
-- Name: commune idx_code_insee; Type: CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.commune
    ADD CONSTRAINT idx_code_insee UNIQUE (s_code_insee);


--
-- Name: liste idx_liste_unq_clef_groupe; Type: CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.liste
    ADD CONSTRAINT idx_liste_unq_clef_groupe UNIQUE (s_groupe, s_clef);


--
-- Name: acte pk_acte_pk_acte; Type: CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.acte
    ADD CONSTRAINT pk_acte_pk_acte PRIMARY KEY (pk_acte);


--
-- Name: authentification pk_authentification_pk_authentification; Type: CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.authentification
    ADD CONSTRAINT pk_authentification_pk_authentification PRIMARY KEY (pk_authentification);


--
-- Name: bien pk_bien_pk_bien; Type: CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.bien
    ADD CONSTRAINT pk_bien_pk_bien PRIMARY KEY (pk_bien);


--
-- Name: commune pk_commune_pk_commune; Type: CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.commune
    ADD CONSTRAINT pk_commune_pk_commune PRIMARY KEY (pk_commune);


--
-- Name: contact pk_contact_pk_contact; Type: CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.contact
    ADD CONSTRAINT pk_contact_pk_contact PRIMARY KEY (pk_contact);


--
-- Name: document pk_document_pk_document; Type: CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.document
    ADD CONSTRAINT pk_document_pk_document PRIMARY KEY (pk_document);


--
-- Name: dossier_acteur pk_dossier_acteur_pk_dossier_acteur; Type: CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.dossier_acteur
    ADD CONSTRAINT pk_dossier_acteur_pk_dossier_acteur PRIMARY KEY (pk_dossier_acteur);


--
-- Name: dossier_bien pk_dossier_bien_pk_dossier_bien; Type: CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.dossier_bien
    ADD CONSTRAINT pk_dossier_bien_pk_dossier_bien PRIMARY KEY (pk_dossier_bien);


--
-- Name: dossier pk_dossier_pk_dossier; Type: CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.dossier
    ADD CONSTRAINT pk_dossier_pk_dossier PRIMARY KEY (pk_dossier);


--
-- Name: favoris pk_favoris_pk_favoris; Type: CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.favoris
    ADD CONSTRAINT pk_favoris_pk_favoris PRIMARY KEY (pk_favoris);


--
-- Name: fichier pk_fichiers_pk_fichiers; Type: CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.fichier
    ADD CONSTRAINT pk_fichiers_pk_fichiers PRIMARY KEY (pk_fichier);


--
-- Name: liste pk_liste_pk_liste; Type: CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.liste
    ADD CONSTRAINT pk_liste_pk_liste PRIMARY KEY (pk_liste);


--
-- Name: logger pk_logger_pk_logger; Type: CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.logger
    ADD CONSTRAINT pk_logger_pk_logger PRIMARY KEY (pk_logger);


--
-- Name: operation pk_operation_pk_operation; Type: CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.operation
    ADD CONSTRAINT pk_operation_pk_operation PRIMARY KEY (pk_operation);


--
-- Name: utilisateur pk_utilisateur_pk_utilisateur; Type: CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.utilisateur
    ADD CONSTRAINT pk_utilisateur_pk_utilisateur PRIMARY KEY (pk_utilisateur);


--
-- Name: document unq_document_fk_fichier; Type: CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.document
    ADD CONSTRAINT unq_document_fk_fichier UNIQUE (fk_fichier);


--
-- Name: bien update_maj_dossier_nsurface; Type: TRIGGER; Schema: foncier; Owner: -
--

CREATE TRIGGER update_maj_dossier_nsurface AFTER UPDATE OF n_surface ON foncier.bien FOR EACH ROW EXECUTE FUNCTION foncier.maj_dossier_nsurface();


--
-- Name: bien update_maj_erreur_cadastrale; Type: TRIGGER; Schema: foncier; Owner: -
--

CREATE TRIGGER update_maj_erreur_cadastrale AFTER UPDATE OF n_surface ON foncier.bien FOR EACH ROW EXECUTE FUNCTION foncier.maj_erreur_cadastrale();


--
-- Name: dossier code_insee_dossier_commune; Type: FK CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.dossier
    ADD CONSTRAINT code_insee_dossier_commune FOREIGN KEY (s_code_insee) REFERENCES foncier.commune(s_code_insee) ON UPDATE CASCADE;


--
-- Name: dossier code_insee_sup_dossier_commune; Type: FK CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.dossier
    ADD CONSTRAINT code_insee_sup_dossier_commune FOREIGN KEY (s_code_insee_supplementaire) REFERENCES foncier.commune(s_code_insee) ON UPDATE CASCADE;


--
-- Name: acte fk_acte_contact; Type: FK CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.acte
    ADD CONSTRAINT fk_acte_contact FOREIGN KEY (fk_service_publicitaire) REFERENCES foncier.contact(pk_contact) ON UPDATE CASCADE;


--
-- Name: acte fk_acte_contact_0; Type: FK CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.acte
    ADD CONSTRAINT fk_acte_contact_0 FOREIGN KEY (fk_geometre) REFERENCES foncier.contact(pk_contact) ON UPDATE CASCADE;


--
-- Name: acte fk_acte_contact_1; Type: FK CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.acte
    ADD CONSTRAINT fk_acte_contact_1 FOREIGN KEY (fk_occupant) REFERENCES foncier.contact(pk_contact) ON UPDATE CASCADE;


--
-- Name: authentification fk_authentification_liste; Type: FK CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.authentification
    ADD CONSTRAINT fk_authentification_liste FOREIGN KEY (fk_liste_profil) REFERENCES foncier.liste(pk_liste) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: authentification fk_authentification_utilisateur; Type: FK CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.authentification
    ADD CONSTRAINT fk_authentification_utilisateur FOREIGN KEY (fk_utilisateur) REFERENCES foncier.utilisateur(pk_utilisateur) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: bien fk_bien_lie; Type: FK CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.bien
    ADD CONSTRAINT fk_bien_lie FOREIGN KEY (fk_bien_lie) REFERENCES foncier.bien(pk_bien) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: bien fk_bien_liste; Type: FK CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.bien
    ADD CONSTRAINT fk_bien_liste FOREIGN KEY (fk_type_bien) REFERENCES foncier.liste(pk_liste) ON UPDATE CASCADE;


--
-- Name: bien fk_bien_liste_1; Type: FK CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.bien
    ADD CONSTRAINT fk_bien_liste_1 FOREIGN KEY (fk_statut) REFERENCES foncier.liste(pk_liste) ON UPDATE CASCADE;


--
-- Name: bien fk_bien_utilisateur; Type: FK CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.bien
    ADD CONSTRAINT fk_bien_utilisateur FOREIGN KEY (fk_utilisateur) REFERENCES foncier.utilisateur(pk_utilisateur) ON UPDATE CASCADE;


--
-- Name: commune fk_commune_liste; Type: FK CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.commune
    ADD CONSTRAINT fk_commune_liste FOREIGN KEY (fk_patrimoine) REFERENCES foncier.liste(pk_liste) ON UPDATE CASCADE;


--
-- Name: document fk_document_fichier; Type: FK CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.document
    ADD CONSTRAINT fk_document_fichier FOREIGN KEY (fk_fichier) REFERENCES foncier.fichier(pk_fichier) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: document fk_document_utilisateur; Type: FK CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.document
    ADD CONSTRAINT fk_document_utilisateur FOREIGN KEY (fk_utilisateur) REFERENCES foncier.utilisateur(pk_utilisateur) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: dossier fk_dossier_acte; Type: FK CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.dossier
    ADD CONSTRAINT fk_dossier_acte FOREIGN KEY (fk_acte) REFERENCES foncier.acte(pk_acte) ON UPDATE CASCADE;


--
-- Name: dossier_acteur fk_dossier_acteur_dossier; Type: FK CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.dossier_acteur
    ADD CONSTRAINT fk_dossier_acteur_dossier FOREIGN KEY (fk_dossier) REFERENCES foncier.dossier(pk_dossier) ON UPDATE CASCADE;


--
-- Name: dossier_acteur fk_dossier_acteur_liste; Type: FK CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.dossier_acteur
    ADD CONSTRAINT fk_dossier_acteur_liste FOREIGN KEY (fk_categorie) REFERENCES foncier.liste(pk_liste) ON UPDATE CASCADE;


--
-- Name: dossier_acteur fk_dossier_acteur_liste_0; Type: FK CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.dossier_acteur
    ADD CONSTRAINT fk_dossier_acteur_liste_0 FOREIGN KEY (fk_type) REFERENCES foncier.liste(pk_liste) ON UPDATE CASCADE;


--
-- Name: dossier_bien fk_dossier_bien_bien; Type: FK CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.dossier_bien
    ADD CONSTRAINT fk_dossier_bien_bien FOREIGN KEY (fk_bien) REFERENCES foncier.bien(pk_bien) ON UPDATE CASCADE;


--
-- Name: dossier_bien fk_dossier_bien_dossier; Type: FK CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.dossier_bien
    ADD CONSTRAINT fk_dossier_bien_dossier FOREIGN KEY (fk_dossier) REFERENCES foncier.dossier(pk_dossier) ON UPDATE CASCADE;


--
-- Name: dossier_bien fk_dossier_bien_liste_0; Type: FK CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.dossier_bien
    ADD CONSTRAINT fk_dossier_bien_liste_0 FOREIGN KEY (fk_mutation_dossier) REFERENCES foncier.liste(pk_liste) ON UPDATE CASCADE;


--
-- Name: dossier fk_dossier_contact; Type: FK CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.dossier
    ADD CONSTRAINT fk_dossier_contact FOREIGN KEY (fk_notaire) REFERENCES foncier.contact(pk_contact) ON UPDATE CASCADE;


--
-- Name: dossier fk_dossier_dossier_acteur; Type: FK CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.dossier
    ADD CONSTRAINT fk_dossier_dossier_acteur FOREIGN KEY (fk_acteur) REFERENCES foncier.dossier_acteur(pk_dossier_acteur) ON UPDATE CASCADE;


--
-- Name: dossier fk_dossier_liste; Type: FK CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.dossier
    ADD CONSTRAINT fk_dossier_liste FOREIGN KEY (fk_type) REFERENCES foncier.liste(pk_liste) ON UPDATE CASCADE;


--
-- Name: dossier fk_dossier_liste_0; Type: FK CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.dossier
    ADD CONSTRAINT fk_dossier_liste_0 FOREIGN KEY (fk_patrimoine) REFERENCES foncier.liste(pk_liste) ON UPDATE CASCADE;


--
-- Name: dossier fk_dossier_liste_1; Type: FK CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.dossier
    ADD CONSTRAINT fk_dossier_liste_1 FOREIGN KEY (fk_mode_dmpc) REFERENCES foncier.liste(pk_liste) ON UPDATE CASCADE;


--
-- Name: dossier fk_dossier_operation; Type: FK CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.dossier
    ADD CONSTRAINT fk_dossier_operation FOREIGN KEY (fk_operation) REFERENCES foncier.operation(pk_operation) ON UPDATE CASCADE;


--
-- Name: dossier fk_dossier_utilisateur; Type: FK CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.dossier
    ADD CONSTRAINT fk_dossier_utilisateur FOREIGN KEY (fk_utilisateur) REFERENCES foncier.utilisateur(pk_utilisateur) ON UPDATE CASCADE;


--
-- Name: favoris fk_favoris_bien; Type: FK CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.favoris
    ADD CONSTRAINT fk_favoris_bien FOREIGN KEY (fk_bien) REFERENCES foncier.bien(pk_bien) ON UPDATE CASCADE;


--
-- Name: favoris fk_favoris_dossier; Type: FK CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.favoris
    ADD CONSTRAINT fk_favoris_dossier FOREIGN KEY (fk_dossier) REFERENCES foncier.dossier(pk_dossier) ON UPDATE CASCADE;


--
-- Name: logger fk_logger_utilisateur; Type: FK CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.logger
    ADD CONSTRAINT fk_logger_utilisateur FOREIGN KEY (fk_utilisateur) REFERENCES foncier.utilisateur(pk_utilisateur) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: dossier fk_provenance_transaction; Type: FK CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.dossier
    ADD CONSTRAINT fk_provenance_transaction FOREIGN KEY (fk_provenance_transaction) REFERENCES foncier.liste(pk_liste) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: contact fk_type_personne; Type: FK CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.contact
    ADD CONSTRAINT fk_type_personne FOREIGN KEY (fk_type_personne) REFERENCES foncier.liste(pk_liste) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: favoris fk_utilisateur_favoris; Type: FK CONSTRAINT; Schema: foncier; Owner: -
--

ALTER TABLE ONLY foncier.favoris
    ADD CONSTRAINT fk_utilisateur_favoris FOREIGN KEY (fk_utilisateur) REFERENCES foncier.utilisateur(pk_utilisateur) ON UPDATE CASCADE;


--
-- PostgreSQL database dump complete
--

